
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 5', N'Сотрудник 5', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 1)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 2', N'Сотрудник 2', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 2)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 3', N'Сотрудник 3', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 3)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 4', N'Сотрудник 4', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 4)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 6', N'Сотрудник 6', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 5)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 7', N'Сотрудник 7', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 6)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 8', N'Сотрудник 8', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 7)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 9', N'Сотрудник 9', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 8)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 10', N'Сотрудник 10', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 9)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 11', N'Сотрудник 11', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 1)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 12', N'Сотрудник 12', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 2)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 13', N'Сотрудник 13', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 3)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 14', N'Сотрудник 14', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 4)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 15', N'Сотрудник 15', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 5)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 16', N'Сотрудник 16', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 6)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 17', N'Сотрудник 17', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 7)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 18', N'Сотрудник 18', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 8)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 19', N'Сотрудник 19', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 9)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 20', N'Сотрудник 20', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 1)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 21', N'Сотрудник 21', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 2)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 22', N'Сотрудник 22', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 3)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 23', N'Сотрудник 23', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 4)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 24', N'Сотрудник 24', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 5)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 25', N'Сотрудник 25', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 6)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 26', N'Сотрудник 26', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 7)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 27', N'Сотрудник 27', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 8)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 28', N'Сотрудник 28', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 9)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 29', N'Сотрудник 29', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 1)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 30', N'Сотрудник 30', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 2)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 31', N'Сотрудник 31', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 3)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 32', N'Сотрудник 32', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 4)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 33', N'Сотрудник 33', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 5)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 34', N'Сотрудник 34', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 6)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 35', N'Сотрудник 35', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 7)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 36', N'Сотрудник 36', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 8)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 37', N'Сотрудник 37', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 9)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 38', N'Сотрудник 38', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 1)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 39', N'Сотрудник 39', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 6)
INSERT INTO [dbo].[Workers] ([firstname], [lastname], [birthday], [address], [department]) VALUES (N'Сотрудник 40', N'Сотрудник 40', DATEFROMPARTS(2011, 11, 11), N'Какой-то адрес', 5)


INSERT INTO [dbo].[Departments] ([id], [Name]) VALUES (1, N'Маркетинг')
INSERT INTO [dbo].[Departments] ([id], [Name]) VALUES (2, N'Бухгалтерия')
INSERT INTO [dbo].[Departments] ([id], [Name]) VALUES (3, N'Продажи')
INSERT INTO [dbo].[Departments] ([id], [Name]) VALUES (4, N'Логистика')
INSERT INTO [dbo].[Departments] ([id], [Name]) VALUES (5, N'Кадры')
INSERT INTO [dbo].[Departments] ([id], [Name]) VALUES (6, N'Безопасность')
INSERT INTO [dbo].[Departments] ([id], [Name]) VALUES (7, N'Дизайн')
INSERT INTO [dbo].[Departments] ([id], [Name]) VALUES (8, N'Поддержка')
INSERT INTO [dbo].[Departments] ([id], [Name]) VALUES (9, N'Координаторы')